
cloud:
  aws: 
    region: 
      static: us-east-2
      
    stack:
      auto: false
    credentials: 
      access-key: AKIAQ3EGP4TNBYAEVE5S

      secret-key: 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
   
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cuencanan
    username: root
    password: ''  

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: debug
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

mvc:
 cors:
  allowed-origins: http://167.172.242.113:9098
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: "*"
  allow-credentials: true
 
server:
  port: 8080


